### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by egasimus** [cournape/samplerate#4]
I'd like to use this with Python 3.4 and librosa, but I can't seem to get it to run prperly -- I get `ImportError`s having to do with relative imports from `version.py` and `info.py`. (I also used to get errors that had to do with `PyString` and `PyBytes`, but those are gone now... strange.) Anyway, how bothersome would it be to get this library to reliably support Python 3.4?

**Comment by markph0204** [comment]
@cournape Can you merge the open PR #5 and get an update in PYPI?

**Comment by greekgoddj** [comment]
@markph0204 Thanks for that pip command, that sorted my issue.

**Comment by ThomasLecocq** [comment]
done with #5
